### ISSUE TITLE
cannot import pylibdmtx in Python 2

### ISSUE THREAD

**Issue by jbweston** [NaturalHistoryMuseum/pylibdmtx#27]
```
jbw@broadway pylibdmtx (master) $ python2 -c 'import pylibdmtx.pylibdmtx'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pylibdmtx/pylibdmtx.py", line 10, in <module>
    from .wrapper import (
  File "pylibdmtx/wrapper.py", line 9, in <module>
    from . import dmtx_library
  File "pylibdmtx/dmtx_library.py", line 8, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

Seems that pathlib was introduced in Python 3.4 [link to docs](https://docs.python.org/3.5/library/pathlib.html), however README and setup.py (and module docstrings) advertise pylibdmtx as Python 2 compatible.

**Comment by quicklizard99** [comment]
The package is indeed Python 2 compatible. For dev activities you should run `pip install -r requirements.pip` to install `pathlib` (and other libs used using development) - https://github.com/NaturalHistoryMuseum/pylibdmtx/blob/master/DEVELOPING.md#development

`requirements.pip` uses environment markers (https://www.python.org/dev/peps/pep-0508/#environment-markers) so that `pathlib`, `mock`, and others are installed only when run by Python 2.7. See https://github.com/NaturalHistoryMuseum/pylibdmtx/blob/master/requirements.pip

**Comment by jbweston** [comment]
Thanks!
